DROP DATABASE IF EXISTS central;
CREATE DATABASE central;
USE central;


    CREATE TABLE users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL
    );
    

    CREATE TABLE budget_entries (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        date DATE,
        amount DECIMAL(10,2),
        category VARCHAR(100),
        description TEXT
    );
    

    CREATE TABLE sleeping_entries (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        date DATE,
        hours FLOAT,
        quality VARCHAR(50),
        notes TEXT
    );
    

    CREATE TABLE sports_sessions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        date DATE,
        time TIME,
        duration FLOAT,
        activity VARCHAR(100),
        location VARCHAR(100)
    );
    

    CREATE TABLE studying_entries (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        date DATE,
        subject VARCHAR(100),
        hours FLOAT,
        productivity INT,
        notes TEXT
    );
    
INSERT INTO users (username, password) VALUES ('Hicham', 'pbkdf2:sha256:600000$pU7QPs7vOY2BtM0p$be7f11f0ed2ba3370377bce304478d3356931b8225c4c25ae029eeccc5f2093f');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-01', 10.94, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-02', 98.31, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-04', 93.43, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-04', 49.51, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-04', 53.15, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-05', 57.13, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-05', 31.71, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-05', 47.02, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-06', 13.83, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-08', 74.72, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-08', 78.57, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-08', 76.26, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-09', 20.29, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-09', 82.67, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-11', 62.56, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-13', 25.62, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-13', 65.66, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-13', 37.92, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-15', 45.46, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-15', 43.98, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-17', 53.34, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-17', 25.6, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-18', 97.34, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-19', 34.6, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-19', 29.14, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-19', 35.8, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-21', 5.34, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-21', 16.93, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-24', 29.4, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-25', 87.08, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-27', 41.69, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-28', 91.32, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-28', 61.11, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-29', 38.91, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-29', 67.61, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-29', 44.04, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-30', 92.3, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-01-30', 40.37, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-01', 89.7, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-01', 22.62, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-01', 12.03, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-02', 49.76, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-02', 47.26, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-02', 65.19, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-04', 45.86, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-05', 88.29, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-07', 85.43, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-07', 85.0, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-07', 34.98, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-08', 90.08, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-10', 73.51, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-11', 88.11, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-11', 35.8, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-11', 79.68, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-12', 5.5, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-13', 65.39, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-13', 23.25, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-15', 79.02, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-15', 59.67, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-16', 72.24, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-16', 80.8, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-17', 79.6, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-17', 97.54, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-17', 22.04, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-18', 80.07, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-18', 57.41, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-20', 21.68, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-21', 18.31, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-21', 56.9, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-21', 14.36, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-22', 31.76, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-22', 90.1, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-22', 96.67, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-23', 16.82, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-23', 96.99, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-24', 97.92, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-25', 30.31, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-27', 20.52, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-27', 11.42, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-02-27', 34.0, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-01', 63.07, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-02', 76.58, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-03', 29.69, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-03', 7.75, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-03', 36.71, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-04', 99.15, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-05', 13.95, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-05', 67.44, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-05', 71.35, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-08', 10.55, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-08', 59.35, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-09', 57.06, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-09', 56.31, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-09', 83.1, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-10', 93.59, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-10', 5.89, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-10', 74.73, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-11', 22.6, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-11', 18.73, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-11', 37.87, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-13', 33.1, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-13', 45.51, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-13', 31.79, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-14', 20.75, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-14', 12.58, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-15', 95.66, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-16', 51.81, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-18', 93.69, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-18', 6.0, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-20', 16.88, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-20', 21.48, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-21', 7.19, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-24', 86.45, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-24', 52.66, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-24', 41.25, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-26', 33.28, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-26', 15.27, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-26', 51.04, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-27', 63.09, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-28', 24.53, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-28', 12.28, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-28', 69.98, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-30', 58.21, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-30', 9.55, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-03-30', 64.52, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-01', 58.7, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-01', 62.36, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-04', 94.85, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-04', 73.32, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-04', 32.47, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-05', 10.57, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-05', 8.48, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-06', 27.05, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-06', 10.84, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-07', 77.38, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-08', 64.19, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-09', 17.17, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-13', 54.15, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-13', 58.48, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-13', 58.25, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-14', 8.92, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-14', 93.77, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-15', 32.47, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-15', 40.83, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-16', 41.81, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-16', 60.08, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-17', 43.78, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-18', 56.29, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-18', 82.99, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-18', 96.9, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-19', 67.87, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-19', 43.32, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-20', 47.55, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-20', 6.78, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-20', 13.77, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-21', 71.57, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-22', 55.71, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-22', 77.43, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-22', 79.4, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-23', 71.79, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-23', 29.9, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-24', 84.4, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-24', 31.6, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-24', 61.44, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-25', 95.89, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-25', 89.65, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-25', 11.66, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-26', 32.49, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-26', 89.01, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-27', 63.34, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-29', 33.95, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-30', 83.1, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-04-30', 66.0, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-01', 90.55, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-02', 95.22, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-03', 38.13, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-04', 6.0, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-04', 30.01, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-05', 63.96, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-05', 23.82, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-05', 58.6, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-07', 67.28, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-07', 62.69, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-08', 34.83, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-10', 13.17, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-10', 71.57, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-11', 84.38, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-11', 89.89, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-12', 31.97, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-12', 68.04, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-14', 90.53, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-14', 26.09, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-15', 87.49, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-16', 57.08, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-16', 93.33, 'Shopping', 'Shopping expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-16', 93.92, 'Entertainment', 'Entertainment expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-17', 50.46, 'Food', 'Food expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-18', 77.34, 'Transport', 'Transport expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-20', 93.84, 'Bills', 'Bills expense');
INSERT INTO budget_entries (user_id, date, amount, category, description) VALUES (1, '2025-05-20', 51.08, 'Bills', 'Bills expense');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-01', 8.4, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-02', 6.9, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-03', 7.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-04', 6.6, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-05', 6.4, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-06', 5.8, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-08', 6.9, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-09', 5.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-10', 7.3, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-12', 8.3, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-13', 8.5, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-14', 5.4, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-15', 6.3, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-16', 9.0, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-18', 5.0, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-19', 8.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-20', 6.0, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-21', 8.7, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-22', 5.1, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-23', 8.8, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-24', 6.8, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-25', 7.0, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-26', 8.0, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-27', 8.8, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-29', 8.6, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-30', 6.6, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-01-31', 5.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-01', 8.9, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-02', 6.3, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-03', 5.9, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-04', 6.8, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-05', 7.1, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-06', 6.8, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-07', 7.0, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-08', 5.7, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-09', 7.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-10', 8.7, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-11', 5.3, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-12', 7.5, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-13', 5.7, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-14', 5.3, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-15', 6.2, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-16', 5.0, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-17', 5.9, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-18', 7.2, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-19', 8.1, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-20', 8.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-21', 7.3, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-22', 5.7, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-23', 8.9, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-24', 5.4, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-25', 5.0, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-26', 6.4, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-27', 8.4, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-02-28', 5.3, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-01', 7.3, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-02', 6.1, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-03', 7.1, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-04', 7.0, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-05', 6.2, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-07', 7.4, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-08', 8.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-09', 5.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-10', 7.6, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-11', 7.7, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-12', 6.9, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-13', 8.0, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-14', 6.9, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-16', 6.3, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-17', 8.0, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-18', 8.2, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-19', 6.8, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-20', 6.0, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-21', 6.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-23', 8.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-25', 7.2, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-26', 9.0, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-27', 7.9, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-28', 7.1, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-29', 7.8, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-30', 7.4, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-03-31', 8.7, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-01', 8.2, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-02', 8.9, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-03', 6.2, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-04', 8.8, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-06', 8.4, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-07', 6.0, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-08', 7.8, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-11', 6.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-13', 7.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-14', 6.0, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-15', 6.0, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-16', 7.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-17', 8.8, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-18', 5.4, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-19', 6.7, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-20', 8.8, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-21', 7.4, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-23', 6.4, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-24', 5.0, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-25', 8.0, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-26', 5.5, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-27', 7.0, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-28', 5.7, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-29', 6.7, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-04-30', 5.3, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-01', 6.7, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-02', 6.7, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-03', 6.5, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-04', 5.5, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-06', 6.9, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-07', 6.9, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-08', 5.4, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-09', 6.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-10', 6.6, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-11', 8.8, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-12', 9.0, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-13', 8.0, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-14', 7.6, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-16', 8.1, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-17', 7.0, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-18', 5.3, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-19', 6.8, 'Poor', 'Sleep quality was poor');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-20', 7.4, 'Fair', 'Sleep quality was fair');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-21', 6.4, 'Good', 'Sleep quality was good');
INSERT INTO sleeping_entries (user_id, date, hours, quality, notes) VALUES (1, '2025-05-22', 8.8, 'Excellent', 'Sleep quality was excellent');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-01', '09:35:00', 1.0, 'Running', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-02', '14:46:00', 1.5, 'Swimming', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-03', '12:54:00', 1.9, 'Gym', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-04', '10:19:00', 0.9, 'Running', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-05', '07:01:00', 1.7, 'Gym', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-06', '16:59:00', 0.8, 'Swimming', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-09', '12:00:00', 0.8, 'Cycling', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-13', '06:44:00', 0.7, 'Running', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-14', '17:05:00', 1.3, 'Swimming', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-16', '09:01:00', 1.5, 'Yoga', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-17', '14:24:00', 1.8, 'Yoga', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-19', '06:10:00', 0.9, 'Cycling', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-20', '18:23:00', 1.3, 'Swimming', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-22', '14:51:00', 0.8, 'Running', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-24', '17:41:00', 0.9, 'Running', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-25', '07:18:00', 1.3, 'Yoga', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-26', '12:21:00', 1.5, 'Cycling', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-28', '09:12:00', 0.6, 'Swimming', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-29', '08:12:00', 0.7, 'Cycling', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-01-30', '10:41:00', 0.7, 'Gym', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-01', '08:09:00', 1.8, 'Running', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-02', '20:18:00', 1.9, 'Yoga', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-03', '08:35:00', 1.4, 'Yoga', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-06', '12:41:00', 0.8, 'Swimming', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-08', '20:03:00', 0.8, 'Running', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-09', '09:08:00', 2.0, 'Cycling', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-11', '11:46:00', 0.9, 'Running', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-13', '13:33:00', 1.5, 'Cycling', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-15', '07:51:00', 0.7, 'Running', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-16', '18:15:00', 1.9, 'Running', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-17', '18:03:00', 1.8, 'Yoga', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-18', '10:02:00', 2.0, 'Cycling', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-19', '18:53:00', 0.9, 'Running', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-23', '13:28:00', 1.7, 'Yoga', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-24', '16:36:00', 1.6, 'Swimming', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-25', '14:55:00', 1.5, 'Cycling', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-26', '20:31:00', 0.7, 'Running', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-27', '16:32:00', 1.2, 'Gym', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-02-28', '13:38:00', 1.0, 'Gym', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-01', '06:22:00', 1.4, 'Swimming', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-03', '10:32:00', 0.9, 'Yoga', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-04', '06:34:00', 1.2, 'Cycling', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-05', '20:49:00', 1.0, 'Yoga', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-06', '09:19:00', 1.2, 'Gym', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-07', '06:07:00', 1.7, 'Gym', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-11', '19:19:00', 1.8, 'Gym', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-12', '17:08:00', 0.6, 'Running', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-13', '07:52:00', 1.3, 'Running', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-14', '18:58:00', 0.5, 'Yoga', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-15', '10:49:00', 0.6, 'Swimming', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-17', '16:26:00', 1.9, 'Gym', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-19', '09:46:00', 0.5, 'Gym', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-20', '10:12:00', 0.6, 'Running', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-21', '19:06:00', 0.9, 'Cycling', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-23', '14:05:00', 1.5, 'Swimming', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-24', '11:55:00', 1.5, 'Yoga', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-25', '17:54:00', 0.5, 'Swimming', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-26', '11:58:00', 1.6, 'Swimming', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-27', '06:24:00', 1.5, 'Swimming', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-29', '10:00:00', 1.8, 'Swimming', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-03-30', '12:20:00', 0.8, 'Gym', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-01', '07:33:00', 0.9, 'Running', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-02', '10:01:00', 1.1, 'Swimming', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-03', '09:18:00', 0.9, 'Swimming', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-05', '18:35:00', 1.2, 'Cycling', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-07', '07:39:00', 1.7, 'Gym', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-08', '10:15:00', 0.9, 'Swimming', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-10', '16:57:00', 0.7, 'Swimming', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-14', '12:11:00', 2.0, 'Yoga', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-15', '18:03:00', 1.7, 'Running', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-16', '20:13:00', 1.4, 'Yoga', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-18', '13:59:00', 1.0, 'Gym', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-21', '08:57:00', 2.0, 'Running', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-22', '17:56:00', 1.8, 'Gym', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-24', '07:10:00', 0.9, 'Running', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-25', '14:34:00', 1.8, 'Cycling', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-27', '18:36:00', 0.8, 'Yoga', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-04-30', '16:27:00', 1.3, 'Yoga', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-01', '20:39:00', 1.2, 'Yoga', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-02', '11:59:00', 0.5, 'Gym', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-04', '17:46:00', 1.2, 'Swimming', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-05', '18:03:00', 0.6, 'Running', 'Park');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-07', '09:49:00', 1.1, 'Yoga', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-08', '09:58:00', 1.8, 'Cycling', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-11', '20:19:00', 1.6, 'Gym', 'Pool');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-12', '06:58:00', 1.5, 'Yoga', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-15', '19:42:00', 1.8, 'Gym', 'Home');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-17', '10:31:00', 0.9, 'Running', 'Track');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-18', '13:08:00', 1.8, 'Yoga', 'Gym');
INSERT INTO sports_sessions (user_id, date, time, duration, activity, location) VALUES (1, '2025-05-22', '14:09:00', 0.7, 'Yoga', 'Park');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-01', 'Math', 3.7, 2, 'Studied Math - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-02', 'Math', 4.7, 10, 'Studied Math - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-04', 'Math', 5.6, 5, 'Studied Math - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-05', 'English', 3.4, 6, 'Studied English - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-06', 'Physics', 1.8, 8, 'Studied Physics - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-07', 'Computer Science', 1.8, 6, 'Studied Computer Science - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-10', 'Computer Science', 4.6, 3, 'Studied Computer Science - Productivity level: 3/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-11', 'Computer Science', 5.1, 5, 'Studied Computer Science - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-14', 'Math', 5.4, 9, 'Studied Math - Productivity level: 9/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-15', 'Physics', 5.7, 5, 'Studied Physics - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-16', 'Computer Science', 2.9, 6, 'Studied Computer Science - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-17', 'Physics', 1.3, 10, 'Studied Physics - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-18', 'History', 4.1, 2, 'Studied History - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-19', 'English', 4.4, 5, 'Studied English - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-21', 'Math', 2.9, 7, 'Studied Math - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-22', 'English', 5.5, 3, 'Studied English - Productivity level: 3/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-23', 'Math', 1.0, 5, 'Studied Math - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-25', 'History', 5.6, 4, 'Studied History - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-26', 'Math', 5.4, 7, 'Studied Math - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-27', 'Math', 5.4, 7, 'Studied Math - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-28', 'Physics', 5.7, 6, 'Studied Physics - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-01-30', 'Computer Science', 2.7, 5, 'Studied Computer Science - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-01', 'Physics', 2.5, 9, 'Studied Physics - Productivity level: 9/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-02', 'Physics', 1.9, 1, 'Studied Physics - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-04', 'Math', 2.8, 2, 'Studied Math - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-07', 'Math', 1.3, 2, 'Studied Math - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-09', 'Math', 5.9, 5, 'Studied Math - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-11', 'History', 5.5, 2, 'Studied History - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-12', 'English', 1.7, 9, 'Studied English - Productivity level: 9/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-14', 'Physics', 2.2, 10, 'Studied Physics - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-16', 'History', 4.1, 1, 'Studied History - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-17', 'Physics', 4.2, 1, 'Studied Physics - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-20', 'Math', 3.4, 7, 'Studied Math - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-21', 'Computer Science', 3.7, 3, 'Studied Computer Science - Productivity level: 3/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-22', 'History', 4.2, 3, 'Studied History - Productivity level: 3/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-23', 'Physics', 3.6, 9, 'Studied Physics - Productivity level: 9/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-24', 'Math', 1.5, 10, 'Studied Math - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-25', 'Math', 5.5, 7, 'Studied Math - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-27', 'History', 1.2, 10, 'Studied History - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-02-28', 'Math', 3.7, 4, 'Studied Math - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-02', 'English', 1.7, 5, 'Studied English - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-03', 'History', 1.8, 1, 'Studied History - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-05', 'History', 3.9, 5, 'Studied History - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-06', 'Physics', 3.7, 4, 'Studied Physics - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-07', 'English', 2.0, 6, 'Studied English - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-08', 'Physics', 3.0, 8, 'Studied Physics - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-09', 'Computer Science', 2.1, 4, 'Studied Computer Science - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-10', 'Physics', 1.4, 9, 'Studied Physics - Productivity level: 9/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-11', 'Computer Science', 4.0, 4, 'Studied Computer Science - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-12', 'Computer Science', 2.0, 5, 'Studied Computer Science - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-13', 'Physics', 4.9, 6, 'Studied Physics - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-14', 'Physics', 1.2, 4, 'Studied Physics - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-15', 'Computer Science', 2.5, 1, 'Studied Computer Science - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-16', 'History', 2.1, 2, 'Studied History - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-17', 'Math', 2.2, 10, 'Studied Math - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-19', 'History', 3.7, 7, 'Studied History - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-20', 'Physics', 2.0, 8, 'Studied Physics - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-21', 'History', 4.2, 6, 'Studied History - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-22', 'Math', 2.0, 7, 'Studied Math - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-23', 'Physics', 2.9, 1, 'Studied Physics - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-24', 'Physics', 3.7, 3, 'Studied Physics - Productivity level: 3/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-25', 'English', 4.0, 7, 'Studied English - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-26', 'English', 4.2, 5, 'Studied English - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-28', 'History', 3.3, 7, 'Studied History - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-03-30', 'English', 1.2, 7, 'Studied English - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-02', 'Math', 5.4, 7, 'Studied Math - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-04', 'Math', 1.1, 6, 'Studied Math - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-05', 'History', 4.8, 5, 'Studied History - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-08', 'Computer Science', 2.5, 10, 'Studied Computer Science - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-09', 'History', 3.8, 8, 'Studied History - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-10', 'Computer Science', 2.4, 10, 'Studied Computer Science - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-12', 'Computer Science', 4.9, 9, 'Studied Computer Science - Productivity level: 9/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-13', 'Computer Science', 1.4, 1, 'Studied Computer Science - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-15', 'Computer Science', 4.6, 8, 'Studied Computer Science - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-16', 'History', 1.2, 9, 'Studied History - Productivity level: 9/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-18', 'English', 4.3, 8, 'Studied English - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-19', 'Computer Science', 4.6, 10, 'Studied Computer Science - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-21', 'Computer Science', 3.2, 1, 'Studied Computer Science - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-23', 'Computer Science', 2.6, 7, 'Studied Computer Science - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-24', 'History', 4.5, 6, 'Studied History - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-25', 'History', 5.6, 2, 'Studied History - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-26', 'English', 3.4, 1, 'Studied English - Productivity level: 1/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-27', 'English', 2.7, 5, 'Studied English - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-04-29', 'English', 2.8, 5, 'Studied English - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-01', 'English', 4.1, 7, 'Studied English - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-02', 'History', 2.9, 4, 'Studied History - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-03', 'History', 4.6, 10, 'Studied History - Productivity level: 10/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-04', 'Math', 3.5, 4, 'Studied Math - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-05', 'Math', 1.7, 2, 'Studied Math - Productivity level: 2/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-06', 'Computer Science', 2.1, 8, 'Studied Computer Science - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-07', 'English', 3.4, 6, 'Studied English - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-09', 'History', 1.3, 4, 'Studied History - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-10', 'English', 5.6, 6, 'Studied English - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-11', 'Computer Science', 3.0, 5, 'Studied Computer Science - Productivity level: 5/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-12', 'Computer Science', 5.8, 6, 'Studied Computer Science - Productivity level: 6/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-13', 'Physics', 2.0, 7, 'Studied Physics - Productivity level: 7/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-16', 'Computer Science', 4.7, 4, 'Studied Computer Science - Productivity level: 4/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-17', 'History', 3.1, 3, 'Studied History - Productivity level: 3/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-19', 'Math', 3.1, 8, 'Studied Math - Productivity level: 8/10');
INSERT INTO studying_entries (user_id, date, subject, hours, productivity, notes) VALUES (1, '2025-05-21', 'Computer Science', 4.1, 4, 'Studied Computer Science - Productivity level: 4/10');
